# Generated by Django 3.2.3 on 2021-06-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=64)),
                ('last_name', models.CharField(default='', max_length=64)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(default='', max_length=64)),
                ('amount', models.IntegerField(default='', max_length=64)),
            ],
        ),
    ]
