# Generated by Django 3.2.3 on 2021-06-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disastermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=64)),
                ('last_name', models.CharField(default='', max_length=64)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(default='', max_length=64)),
                ('amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=64)),
                ('last_name', models.CharField(default='', max_length=64)),
                ('phone', models.BigIntegerField()),
                ('altphone', models.BigIntegerField()),
                ('email', models.EmailField(default='', max_length=64)),
                ('gender', models.CharField(default='', max_length=64)),
                ('age', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=200)),
                ('bloodgroup', models.CharField(default='', max_length=64)),
                ('aadhar', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Donors',
        ),
    ]
