# Generated by Django 3.2.3 on 2021-06-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disastermanagement', '0002_auto_20210617_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
