# Generated by Django 3.2.3 on 2021-06-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disastermanagement', '0004_auto_20210617_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='service1',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='service2',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='service3',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='service4',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='service5',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='service6',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='service7',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='service', to='disastermanagement.Social'),
        ),
    ]
