# Generated by Django 3.2.3 on 2021-06-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disastermanagement', '0005_auto_20210617_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='service',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='service',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
