# Generated by Django 3.2.3 on 2021-06-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disastermanagement', '0006_auto_20210617_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='General_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Grocerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Rescue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(default='', max_length=64)),
            ],
        ),
    ]
