# Generated by Django 3.2.3 on 2021-06-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disastermanagement', '0007_chemist_general_store_grocerie_hospital_rescue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemist',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chemist',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='general_store',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='general_store',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='grocerie',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grocerie',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='rescue',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rescue',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=64, null=True),
        ),
    ]
